extends Resource
class_name TroopSummaryBuilder


func build_combat_summary(troop) -> Dictionary:
	var summary: Dictionary = troop._get_combat_stat_cache(true).duplicate()
	summary.merge({
		"food_shortage_ratio": troop._food_shortage_ratio,
		"combat_target": troop._active_enemy.get_path() if troop._is_valid_enemy(troop._active_enemy) else NodePath(""),
		"in_combat": troop._state == troop.STATE_FIGHTING,
		"engagement_range_m": troop._get_mode_engagement_range(),
		"attack_zone_corners": troop.get_attack_zone_corners(),
		"attack_zone_corner_count": troop.get_attack_zone_corners().size(),
		"combat_scatter_active": troop._combat_scatter_active,
		"combat_assigned_target_count": troop._combat_soldier_targets.size(),
		"combat_locked_attacker_count": troop._combat_soldier_lock_positions.size(),
		"combat_max_target_load": troop._get_max_combat_target_load(),
		"combat_socket_assignment_count": troop._combat_soldier_socket_indices.size(),
		"combat_render_dirty_soldier_count": troop._combat_render_dirty_soldiers.size(),
		"combat_touched_soldier_count": troop._combat_touched_soldiers.size(),
		"combat_debug_line_pair_count": troop._combat_debug_line_pair_count,
		"combat_debug_line_coming_pair_count": troop._combat_debug_line_coming_pair_count,
		"combat_debug_line_fighting_pair_count": troop._combat_debug_line_fighting_pair_count,
		"combat_target_coming_count": troop._get_combat_relation_status_count(troop.COMBAT_RELATION_COMING),
		"combat_target_fighting_count": troop._get_combat_relation_status_count(troop.COMBAT_RELATION_FIGHTING),
		"combat_visual_stance_update_count": troop._combat_visual_stance_update_count,
		"combat_visual_thrust_count": troop._combat_visual_thrust_count,
		"pending_departed_soldier_count": troop._pending_departed_soldiers.size(),
		"combat_perf_active_cache_rebuilds": troop._combat_perf_active_cache_rebuilds,
		"combat_perf_target_candidate_scans": troop._combat_perf_target_candidate_scans,
		"combat_perf_separation_pair_checks": troop._combat_perf_separation_pair_checks,
		"combat_perf_steering_updates": troop._combat_perf_steering_updates,
		"formation_target_write_count": troop._formation_target_write_count,
		"formation_target_skip_count": troop._formation_target_skip_count,
		"moving_formation_pair_checks": troop._moving_formation_pair_checks,
		"spatial_grid_rebuilds": troop._spatial_grid_rebuilds,
		"combat_socket_clamp_count": troop._combat_socket_clamp_count,
		"logic_sleeping_soldier_count": troop._get_logic_sleeping_soldier_count(),
		"combat_perf_target_scans_per_second": troop._combat_perf_target_scans_per_second,
		"combat_perf_pair_checks_per_second": troop._combat_perf_pair_checks_per_second,
		"combat_perf_steering_updates_per_second": troop._combat_perf_steering_updates_per_second,
		"perf_last_physics_usec": troop._perf_last_physics_usec,
		"perf_max_physics_usec": troop._perf_max_physics_usec,
		"perf_last_combat_tick_usec": troop._perf_last_combat_tick_usec,
		"perf_max_combat_tick_usec": troop._perf_max_combat_tick_usec,
		"perf_last_combat_collect_usec": troop._perf_last_combat_collect_usec,
		"perf_max_combat_collect_usec": troop._perf_max_combat_collect_usec,
		"perf_last_combat_spatial_usec": troop._perf_last_combat_spatial_usec,
		"perf_max_combat_spatial_usec": troop._perf_max_combat_spatial_usec,
		"perf_last_combat_assign_usec": troop._perf_last_combat_assign_usec,
		"perf_max_combat_assign_usec": troop._perf_max_combat_assign_usec,
		"perf_last_combat_motion_usec": troop._perf_last_combat_motion_usec,
		"perf_max_combat_motion_usec": troop._perf_max_combat_motion_usec,
		"perf_last_formation_separation_usec": troop._perf_last_formation_separation_usec,
		"perf_max_formation_separation_usec": troop._perf_max_formation_separation_usec,
		"perf_last_combat_summary_usec": troop._perf_last_combat_summary_usec,
		"perf_max_combat_summary_usec": troop._perf_max_combat_summary_usec,
		"perf_stat_worker_wait_count": troop._perf_stat_worker_wait_count,
		"stat_worker_completed_job_polls": troop._stat_worker_completed_job_polls,
		"stat_worker_blocking_waits": troop._stat_worker_blocking_waits,
		"engagement_windup_seconds": troop._engagement_windup_remaining,
		"manual_attack_target": troop._manual_attack_target.get_path() if troop._is_valid_enemy(troop._manual_attack_target) else NodePath(""),
		"survivor_rout_triggered": troop._survivor_rout_triggered,
		"defeated": int(summary.get("active_soldier_count", 0)) <= 0,
	}, true)
	summary.merge(troop._get_soldier_render_batch_summary(), true)
	return summary
